# Generated by Django 5.2.7 on 2025-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagel_law_portal', '0002_category_alter_forms_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'upload file',
                'verbose_name_plural': 'uploaded files',
                'db_table': 'upload_file',
            },
        ),
    ]
