# Generated by Django 5.2.7 on 2025-11-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagel_law_portal', '0003_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
